# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24207cedced43ac4365596ac5f9615c2f516c048a7b9815a05ada6fb160023d6a49281925f2a278a36ccfb4c0ae88692e9c3951e3d796d23ae642077b58705d2

test:
  secret_key_base: 669826c08bdce7170fbce6fbbe2d94eeaef958f951eac362cd3aeb049264a6d008bf7b6835861042231488faeebccc27ac43b720a8dcc4f3f18805858fb28878

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
